# Generated by Django 4.2.30 on 2026-09-28 08:23

import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0023_alter_benefitattachment_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duplicates', to='payroll.csvreconciliationupload'),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='matched_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='paid_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='storage_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='total_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='unmatched_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvreconciliationupload',
            name='unpaid_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.csvreconciliationupload'),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='matched_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='paid_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='storage_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='total_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='unmatched_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcsvreconciliationupload',
            name='unpaid_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvreconciliationupload',
            name='status',
            field=models.CharField(choices=[('TRIGGERED', 'Triggered'), ('VALIDATING', 'Validating'), ('IN_PROGRESS', 'In progress'), ('PENDING_REVIEW', 'Pending review'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('WAITING_FOR_VERIFICATION', 'WAITING_FOR_VERIFICATION'), ('FAIL', 'Fail'), ('DUPLICATE', 'Duplicate')], default='TRIGGERED', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcsvreconciliationupload',
            name='status',
            field=models.CharField(choices=[('TRIGGERED', 'Triggered'), ('VALIDATING', 'Validating'), ('IN_PROGRESS', 'In progress'), ('PENDING_REVIEW', 'Pending review'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('WAITING_FOR_VERIFICATION', 'WAITING_FOR_VERIFICATION'), ('FAIL', 'Fail'), ('DUPLICATE', 'Duplicate')], default='TRIGGERED', max_length=255),
        ),
        migrations.CreateModel(
            name='ReconciliationUploadRow',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('row_number', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_data', models.JSONField(default=dict)),
                ('mismatch_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], default='VALID', max_length=16)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.benefitconsumption')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rows', to='payroll.csvreconciliationupload')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReconciliationUploadRow',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('row_number', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_data', models.JSONField(default=dict)),
                ('mismatch_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], default='VALID', max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('benefit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.benefitconsumption')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.csvreconciliationupload')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reconciliation upload row',
                'verbose_name_plural': 'historical reconciliation upload rows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
