# Generated by Django 4.2.30 on 2026-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_reconciliation_upload_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreconciliationuploadrow',
            name='mismatch_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reconciliationuploadrow',
            name='mismatch_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
